trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  appDir: kitchen-site

steps:
- task: NodeTool@0
  displayName: node install
  inputs:
    versionSpec: '12.x'

- script: npm install
  displayName: npm install
  workingDirectory: $(appDir)

- script: npx ng build --prod
  displayName: ng build
  workingDirectory: $(appDir)

- script: npx ng test
    --browsers ChromeHeadless
    --no-watch
    --code-coverage
  displayName: ng test
  workingDirectory: $(appDir)

# requires some extra work iirc
- script: npx ng e2e
  displayName: ng e2e
  workingDirectory: $(appDir)
  enabled: false

- script: npx ng lint
  displayName: ng lint
  workingDirectory: $(appDir)

- task: SonarCloudPrepare@1
  displayName: sonarcloud prepare
  inputs:
    SonarCloud: 'sonarcloud-escalonn'
    organization: '2006-jun15-net'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '2006-jun15-net_nick-project2-kitchen-site'
    cliSources: '$(appDir)/src,$(appDir)/e2e'
    extraProperties: |
      sonar.coverage.exclusions=**/*.spec.ts,$(appDir)/e2e/**/*
      sonar.typescript.lcov.reportPaths=$(appDir)/coverage/$(appDir)/lcov.info

- task: SonarCloudAnalyze@1
  displayName: sonarcloud run

- task: SonarCloudPublish@1
  displayName: sonarcloud publish
  inputs:
    pollingTimeoutSec: '300'

- task: AzureRmWebAppDeployment@4
  displayName: azure app service deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(1)(0518cd5b-d389-4983-9496-cdcae31dcc60)'
    appType: 'webApp'
    WebAppName: '2006-kitchen-site'
    packageForLinux: '$(appDir)/dist/$(appDir)'
